
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sHIVAM
 */
public class checkBox extends javax.swing.JPanel {

          /**
           * Creates new form checkBox
           */
          public checkBox() {
                    initComponents();
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
          @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jPanel1 = new javax.swing.JPanel();
                    jCheckBox1 = new javax.swing.JCheckBox();
                    jCheckBox2 = new javax.swing.JCheckBox();

                    jCheckBox1.setText("A");
                    jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
                              public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                        jCheckBox1StateChanged(evt);
                              }
                    });
                    jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jCheckBox1ActionPerformed(evt);
                              }
                    });

                    jCheckBox2.setText("B");
                    jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
                              public void stateChanged(javax.swing.event.ChangeEvent evt) {
                                        jCheckBox2StateChanged(evt);
                              }
                    });
                    jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jCheckBox2ActionPerformed(evt);
                              }
                    });

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jCheckBox2)
                                                  .addComponent(jCheckBox1))
                                        .addContainerGap(252, Short.MAX_VALUE))
                    );
                    jPanel1Layout.setVerticalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(jCheckBox1)
                                        .addGap(29, 29, 29)
                                        .addComponent(jCheckBox2)
                                        .addContainerGap(119, Short.MAX_VALUE))
                    );

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                    this.setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
          }// </editor-fold>//GEN-END:initComponents

          private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
                    // TODO add your handling code here:
                    if(!jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
                              JOptionPane.showMessageDialog(null, "B is selected");
                    }
                    else if(jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
                              JOptionPane.showMessageDialog(null, "A and B are selected");
                    }
          }//GEN-LAST:event_jCheckBox2ActionPerformed

          private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
                    // TODO add your handling code here:
                    if(jCheckBox1.isSelected() && !jCheckBox2.isSelected()) {
                              JOptionPane.showMessageDialog(null, "A is selected");
                    }
                    else if(jCheckBox1.isSelected() && jCheckBox2.isSelected()) {
                              JOptionPane.showMessageDialog(null, "A and B are selected");
                    }
          }//GEN-LAST:event_jCheckBox1ActionPerformed

          private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
                    // TODO add your handling code here:
                    if(!jCheckBox1.isSelected())
                              JOptionPane.showMessageDialog(null, "A is not selected");
          }//GEN-LAST:event_jCheckBox1StateChanged

          private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
                    // TODO add your handling code here:
                    if(!jCheckBox2.isSelected())
                              JOptionPane.showMessageDialog(null, "A is not selected");
          }//GEN-LAST:event_jCheckBox2StateChanged

          
public static void main(String args[]) {
                    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                     */
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Nimbus".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(check1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(check1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(check1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(check1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
        //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new checkBox().setVisible(true);
                              }
                    });
          }
          
          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JCheckBox jCheckBox1;
          private javax.swing.JCheckBox jCheckBox2;
          private javax.swing.JPanel jPanel1;
          // End of variables declaration//GEN-END:variables
}
